// Generated by tools/png-to-drawing.ts from art/drawings: do not edit.
// Change the PNG or art/drawings/drawings.json, then run `pnpm drawings`.

import type { Drawing } from './drawings.ts';

export const HEART: Drawing = {
  id: 'heart',
  name: 'Heart',
  legend: { H: 'red' },
  rows: [
    '..HHH...HHH..',
    '.HHHHH.HHHHH.',
    'HHHHHHHHHHHHH',
    'HHHHHHHHHHHHH',
    'HHHHHHHHHHHHH',
    '.HHHHHHHHHHH.',
    '..HHHHHHHHH..',
    '...HHHHHHH...',
    '....HHHHH....',
    '.....HHH.....',
    '......H......',
  ],
};

export const BUTTERFLY: Drawing = {
  id: 'butterfly',
  name: 'Butterfly',
  legend: { O: 'orange', Y: 'yellow', B: 'brown' },
  rows: [
    '....OOO.......OOO....',
    '..OOOOOO.....OOOOOO..',
    '.OOOOOOOO...OOOOOOOO.',
    '.OOOOOOOOO.OOOOOOOOO.',
    '.OOOOOOOOOBOOOOOOOOO.',
    '..OOOOOOOOBOOOOOOOO..',
    '...OOOOOOOBOOOOOOO...',
    '....OOOOOOBOOOOOO....',
    '...YYYYYYOBOYYYYYY...',
    '..YYYYYYYYBYYYYYYYY..',
    '..YYYYYYYYBYYYYYYYY..',
    '...YYYYYYYBYYYYYYY...',
    '....YYYYYYBYYYYYY....',
    '.....YYYY.B.YYYY.....',
    '......YY..B..YY......',
  ],
};

export const MAPLE_LEAF: Drawing = {
  id: 'maple-leaf',
  name: 'Maple Leaf',
  legend: { R: 'red', B: 'brown' },
  rows: [
    '........R........',
    '.......RRR.......',
    '.......RRR.......',
    '..R...RRRRR...R..',
    '..RR..RRRRR..RR..',
    '...RRRRRRRRRRR...',
    'R..RRRRRRRRRRR..R',
    'RR.RRRRRRRRRRR.RR',
    '.RRRRRRRRRRRRRRR.',
    '..RRRRRRRRRRRRR..',
    '...RRRRRRRRRRR...',
    '..RRRRRRRRRRRRR..',
    '.RRRRRRRRRRRRRRR.',
    '....RRRRRRRRR....',
    '......RRRRR......',
    '........B........',
    '........B........',
    '........B........',
  ],
};

export const ACORN: Drawing = {
  id: 'acorn',
  name: 'Acorn',
  legend: { B: 'brown', O: 'orange', G: 'green' },
  rows: [
    '.......B.....GG',
    '.......B...GGGG',
    '......BBB.GGGG.',
    '...BBBBBBBBBG..',
    '..BBBBBBBBBBB..',
    '.BBBBBBBBBBBBB.',
    '.BBBBBBBBBBBBB.',
    '..OOOOOOOOOOO..',
    '..OOOOOOOOOOO..',
    '..OOOOOOOOOOO..',
    '..OOOOOOOOOOO..',
    '...OOOOOOOOO...',
    '...OOOOOOOOO...',
    '....OOOOOOO....',
    '.....OOOOO.....',
    '......OOO......',
    '.......O.......',
  ],
};

/** Every drawing, in the order of art/drawings/drawings.json. */
export const ART: readonly Drawing[] = [HEART, BUTTERFLY, MAPLE_LEAF, ACORN];
