import type { Rng } from '../rng/rng.ts';

/** Adjective + noun, like the reference game's "Wonderful Butterfly". */
export const ADJECTIVES: readonly string[] = [
  'Wonderful',
  'Exquisite',
  'Smart',
  'Colorful',
  'Brave',
  'Calm',
  'Clever',
  'Curious',
  'Dreamy',
  'Eager',
  'Fancy',
  'Gentle',
  'Happy',
  'Jolly',
  'Kind',
  'Lucky',
  'Merry',
  'Nimble',
  'Peaceful',
  'Quick',
  'Radiant',
  'Shiny',
  'Sleepy',
  'Sunny',
  'Swift',
  'Tiny',
  'Witty',
  'Zesty',
  'Bold',
  'Bright',
  'Cozy',
  'Dapper',
  'Fluffy',
  'Golden',
  'Humble',
  'Jumpy',
  'Lively',
  'Mighty',
  'Noble',
  'Plucky',
  'Quiet',
  'Rosy',
  'Silver',
  'Snug',
  'Spry',
  'Sturdy',
  'Vivid',
  'Wild',
  'Breezy',
  'Chirpy',
  'Dizzy',
  'Frosty',
  'Giddy',
  'Glossy',
  'Groovy',
  'Misty',
  'Perky',
  'Sparkly',
];

export const NOUNS: readonly string[] = [
  'Butterfly',
  'Ant',
  'Dog',
  'Cloud',
  'Fox',
  'Owl',
  'Panda',
  'Otter',
  'Rabbit',
  'Koala',
  'Dolphin',
  'Falcon',
  'Hedgehog',
  'Lion',
  'Moose',
  'Parrot',
  'Penguin',
  'Puffin',
  'Raccoon',
  'Seal',
  'Sparrow',
  'Tiger',
  'Turtle',
  'Whale',
  'Zebra',
  'Comet',
  'Meadow',
  'Pebble',
  'River',
  'Maple',
  'Acorn',
  'Beetle',
  'Cactus',
  'Daisy',
  'Ember',
  'Fern',
  'Glacier',
  'Harbor',
  'Island',
  'Juniper',
  'Kite',
  'Lantern',
  'Marble',
  'Nutmeg',
  'Orchid',
  'Pepper',
  'Quill',
  'Ribbon',
  'Saffron',
  'Thistle',
  'Umbrella',
  'Violet',
  'Walnut',
  'Yarn',
  'Zephyr',
  'Breeze',
  'Canyon',
  'Dune',
  'Flame',
  'Grove',
];

/** `count` distinct character names from one stream. */
export function characterNames(rng: Rng, count: number): string[] {
  const maxDistinct = ADJECTIVES.length * NOUNS.length;
  if (count > maxDistinct) throw new RangeError(`Only ${maxDistinct} distinct names exist`);
  const names = new Set<string>();
  while (names.size < count) names.add(`${rng.pick(ADJECTIVES)} ${rng.pick(NOUNS)}`);
  return [...names];
}
